name: CI Pipeline Release

on:
  release:
    types: [created]

jobs:
  build-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run build

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.0
        with:
          type: 'zip'
          filename: 'keywind-release-${{github.ref_name}}.zip'
          path: 'theme/keywind'
      
      - uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "keywind-release-${{github.ref_name}}.zip"
          release_id: "v${{github.ref_name}}"
          overwrite: true
          verbose: true
